steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Unit Test Image'
  args: [ 'build', 'test' , '-t', 'gcr.io/${_REPO_ID}/${_NAMESPACE}/${_TEST_APP}:latest' ]
  
- name: 'gcr.io/cloud-builders/docker'
  id: 'Run Unit Test Image'
  args: ['run', 'gcr.io/${_REPO_ID}/${_NAMESPACE}/${_TEST_APP}:latest' ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Application Image'
  args:
  - 'build'
  - '.'
  - '-t'
  - 'gcr.io/${_REPO_ID}/${_NAMESPACE}/${_APP}:latest'
  - '-t'
  - 'gcr.io/${_REPO_ID}/${_NAMESPACE}/${_APP}:$SHORT_SHA'

- name: "gcr.io/cloud-builders/gsutil"
  id: 'Copy Helm Files to Cloud Storage'
  dir: cicd
  args: ['cp', '-Z', 'helm/values*yaml', 'gs://${_REPO_ID}-kubernetes-manifests/${_NAMESPACE}/']

images:
- 'gcr.io/${_REPO_ID}/${_NAMESPACE}/${_TEST_APP}:latest'
- 'gcr.io/${_REPO_ID}/${_NAMESPACE}/${_APP}:latest'
- 'gcr.io/${_REPO_ID}/${_NAMESPACE}/${_APP}:$SHORT_SHA'

substitutions:
  _APP: your-app
  _TEST_APP: test-${_APP}
  _NAMESPACE: cluster-2
  _REPO_ID: cio-gke-devops-e4993356
