steps:

  - id: 'Get infrastructure repo'
    name: gcr.io/cloud-builders/git
    args: [ 'clone', 'https://github.com/1Basile/tf-infra-your-app' ]

  - id: 'tf plan'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd tf-infra-your-app/terraform/environments/
        for dir in */
        do
          cd ${dir}
          terraform init
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../
        done