steps:

  - id: 'Get infrastructure repo'
    name: gcr.io/cloud-builders/git
    args: [ 'clone', 'https://github.com/1Basile/tf-infra-your-app' ]

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd tf-infra-your-app/terraform/environments/stage
        terraform init
        terraform apply -auto-approve